### ISSUE TITLE
Exception when creating a type alias of WithAnnotations[MyModel, MyTypedDict]

### ISSUE THREAD

**Issue by cuu508** [typeddjango/django-stubs#1760] opened 2023-10-06 13:00 UTC
# Bug report

## What's wrong

To make my code easier to read and less repetitive I would like to create a type alias for `WithAnnotations[model_cls, typeddict_cls]` and use it in function signatures. An example:

```python
from __future__ import annotations

from typing import TypedDict

from django.db import models
from django_stubs_ext import WithAnnotations


class MyModel(models.Model):
    username = models.CharField(max_length=100)


class MyTypedDict(TypedDict):
    foo: str


AnnotatedModel = WithAnnotations[MyModel, MyTypedDict]


def func2(m: AnnotatedModel) -> str:
    return m.foo  # OK, since we said field "foo" was allowed
```

If I save this as `experiment.py` in my Django project's root directory, mypy is happy:

```
mypy --strict --follow-imports silent experiment.py 
Success: no issues found in 1 source file
```

If I instead save the exact same file it in my app's `admin.py` file, I get an error:

```
mypy --strict --follow-imports silent hc/api/admin.py 
Error constructing plugin instance of NewSemanalDjangoPlugin

Traceback (most recent call last):
  File "/home/user/venvs/healthchecks/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 94, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 195, in build
  File "mypy/build.py", line 240, in _build
  File "mypy/build.py", line 503, in load_plugins
  File "mypy/build.py", line 484, in load_plugins_from_config
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/mypy_django_plugin/main.py", line 64, in __init__
    self.django_context = DjangoContext(self.plugin_config.django_settings_module)
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/mypy_django_plugin/django/context.py", line 84, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/mypy_django_plugin/django/context.py", line 68, in initialize_django
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/repos/healthchecks/hc/api/admin.py", line 17, in <module>
    AnnotatedModel = WithAnnotations[MyModel, MyTypedDict]
  File "/usr/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/typing.py", line 1058, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/home/user/venvs/healthchecks/lib/python3.10/site-packages/typing_extensions.py", line 164, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too many parameters for typing.Annotated[~_T, django_stubs_ext.annotations.Annotations[+_Annotations]]; actual 2, expected 1
```

I also get the same exception when I try to run `manage.py` commands, for example, `manage.py runserver`.

## How is that should be

The example above should produce no type warnings.

## System information

- OS:
- `python` version: 3.10.12
- `django` version: 4.2.6
- `mypy` version: 1.5.1
- `django-stubs` version: 4.2.4
- `django-stubs-ext` version: 4.2.2

**Comment by nikvst** [comment] 2024-04-24 12:28
Isn’t this the same error as https://github.com/typeddjango/django-stubs/issues/719 ?

**Comment by flaeppe** [comment] 2024-04-24 13:47
@nikvst I agree that it sure looks like a duplicate of #719

**Closed as not planned by flaeppe** 2024-04-24 13:47 UTC
Labels: bug
