### ISSUE TITLE
Enable django-stubs to recognise members of a Model introduced through related_name argument

### ISSUE THREAD

**Issue by himanshu-balasamanta** [typeddjango/django-stubs#878] opened 2022-03-17 11:01 UTC
```python
class Question(models.Model):
    ...
    
class Choice(models.Model):
    question_id = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='choice_set')
    ...
```
django-stubs isn't able to recognise choice_set as a member of Question model.
```python
reveal_type(question.choice_set.create(choice_text='django'))
```
Throws error `"Question" has no attribute "choice_set"`

Would like to take it up, need suggestions on how to proceed.

**Comment by ljodal** [comment] 2022-03-28 16:44
This is supported, but it seems to break if you use a custom QuerySet this way:

```python
class MyQuerySet(models.QuerySet):
    pass


class MyModel(models.Model):
    objects = MyQuerySet.as_manager()
```

You can use the workaround described in [README.md](https://github.com/typeddjango/django-stubs#my-queryset-methods-are-returning-any-rather-than-my-model):

```python
class MyQuerySet(models.QuerySet):
    pass

MyManager = models.Manager.from_queryset(MyQuerySet)

class MyModel(models.Model):
    objects = MyManager()
```

At least this seemed to fix the issue in one of my projects. This seems to be a regression in recent `django-stubs` releases though, as this previously worked even if the manager wasn't defined in a way that mypy understood.

**Comment by MrkGrgsn** [comment] 2022-04-07 03:11
I'm getting this same warning with 1.10/Django 3.2 where I wasn't when using 1.7/Django 2.2. I don't get the warning if I rollback to 1.9.  It's even occurring for models using the default manager.

**Comment by ljodal** [comment] 2022-04-07 07:32
You might also be affected by https://github.com/typeddjango/django-stubs/pull/902, which is in master but is not released on pypi yet

**Comment by MrkGrgsn** [comment] 2022-04-08 01:08
Thanks for the pointer @ljodal, using master resolves the issues for me.

**Comment by intgr** [comment] 2022-11-08 13:42
Closing per MrkGrgsn's comment.

**Closed as completed by intgr** 2022-11-08 13:42 UTC
