### ISSUE TITLE
mypy incremental run shows errors not present in initial mypy run

### ISSUE THREAD

**Issue by danifus** [typeddjango/django-stubs#432] opened 2020-07-29 05:28 UTC
# Bug report

## What's wrong

I've created a reproduction project: https://github.com/danifus/djstubs-reproduce2

This may be related to #423 (so the reproduction is an extension of that).

It looks like the methods on the manager of the inherited base model are not being defined the same way in initial and incremental runs.

- pip install django and django-stubs from git (I'm testing on 3915aa06392f4cd104c5f3c27cfca198d86d247b)
- cd to directory containing mypy.ini
- make sure the `.mypy_cache` dir is not present
- run mypy .
    Produces the expected output:
    ```
    second_app/models.py:10: error: Incompatible types in assignment (expression has type "str", variable has type "int")
    Found 1 error in 1 file (checked 28 source files)
    ```
- run mypy .
    Produces an error that wasn't in the initial run:
    ```
    test_app/models.py:14: error: Unexpected keyword argument "arg1" for "movie_method" of "ModelA_MovieManager1"
    second_app/models.py:10: error: Incompatible types in assignment (expression has type "str", variable has type "int")
    Found 2 errors in 2 files (checked 28 source files)
    ```

## How is that should be
Subsequent incremental runs should produce the same output as the initial run

## System information

- OS: mac
- `python` version: 3.8.4
- `django` version: 3.0.8
- `mypy` version: 0.782
- `django-stubs` version: commit 3915aa06392f4cd104c5f3c27cfca198d86d247b

**Comment by flaeppe** [comment] 2024-04-24 14:05
There's been quite a lot of changes around custom methods on querysets/managers since this issue was reported. I tried to reproduce it but wasn't able to. I'll close this, feel free to open a new issue or provide a new repro case and I'll reopen.

**Closed as completed by flaeppe** 2024-04-24 14:05 UTC
Labels: bug
