### ISSUE TITLE
Subclassed models with related_name relations do not have dynamically generated annotations.

### ISSUE THREAD

**Issue by Winspear** [typeddjango/django-stubs#1988] opened 2024-03-04 08:47 UTC
# Bug report

Hello,
I initially wrote the following in "discussions" but was encouraged to raise the issue as a bug instead;

Throughout my codebase I have a number of related_name relations defined. For most, django-stubs (latest release) seems to be generating the requisite annotations to make MyPy pass, but for certain models the annotation is not being generated. One example of this is a more complicated structure than a simple model to model, foreign key reference, as it subclasses an existing model, eg:
```
class BaseImage(models.Model):
    image = models.ImageField(blank=True)

class FruitImage(BaseImage):
    fruit = models.OneToOneField(
        Fruit,
        related_name="image")

class Fruit(models.Model):
    name = models.CharField(max_length=10)
```

With this particular structure, I am receiving the mypy error "Fruit" has no attribute "image"

I would expect however that the annotations would be generated for the image attribute on Fruit. 

- OS:
- `python` version: 3.10.x
- `django` version: 4.2.10
- `mypy` version: 1.8.0
- `django-stubs` version: 4.2.7
- `django-stubs-ext` version: 4.2.7

**Comment by flaeppe** [comment] 2024-03-21 14:34
I've attempted to but cannot reproduce the issue you describe with the above snippet.

Could there be something else that interferes with your models and/or fields?

Since it's a reverse relation it needs the mypy plugin to be active, have you enabled it?

**Comment by nijel** [comment] 2024-03-21 15:23
Maybe I've hit this as well. without further investigation I've added type hints to the model (the commit is linked above). But it's on a complex codebase and I really didn't have time to investigate the root cause.

**Comment by flaeppe** [comment] 2024-03-22 11:13
Without any repro I don't see what we can do here. I'm going to close this off for now, I'm happy to reopen if any of you find a repro case.

**Closed as completed by flaeppe** 2024-03-22 11:13 UTC
Labels: bug

**Comment by nijel** [comment] 2024-03-22 14:20
Okay, for us the root cause was referencing affected model as "Model" instead of "app.Model". For some reason that blocked all reverse fields from being added. https://github.com/WeblateOrg/weblate/commit/e454371f385f258a28f7e819d1599a524d240163 fixed that

**Comment by Winspear** [comment] 2024-05-07 17:45
Just reporting back to say that as of django stubs latest release (5.0.0), this is resolved for us.
