### ISSUE TITLE
Wrong type annotation for create method of a Manager

### ISSUE THREAD

**Issue by tcleonard** [typeddjango/django-stubs#578] opened 2021-03-19 16:22 UTC
# Bug report

## What's wrong

Queryset manager `create` method has the wrong type definition, it seems to expect a queryset type back I think.
Mypy raises an error when trying to override the original `create` method.

For example:
```python
class MyModelManager(models.Manager):

    def create(self, *args, **kwargs) -> MyModel:
          return super().create(*args, **kwargs)


class MyModel(models.Model):

   objects = MyModelManager()
```

raises the following error:
```
Signature of "create" incompatible with supertype "_BaseQuerySet"
```

## System information

- OS: Linux
- `python` version: 3.8
- `django` version: 3.1.7
- `mypy` version: 0.790
- `django-stubs` version: 1.7.0

**Comment by sobolevn** [comment] 2021-03-19 17:54
Can you please try to replace `*args, **kwargs` with the precise signature?

**Comment by tcleonard** [comment] 2021-03-20 08:44
which should be? You mean listing all model attributes?

**Comment by sobolevn** [comment] 2021-03-20 20:46
Oh, I am sorry 🙂 
I have read your original post incorrectly. 

Can you please try to use `class MyModelManager(models.Manager[MyModel]):` instead?

**Comment by tcleonard** [comment] 2021-03-24 19:10
I still get the same error

**Comment by tcleonard** [comment] 2021-03-24 19:49
my error was not due to the return type of the create (I was changing the types of some of the arguments of the method)

**Comment by tcleonard** [comment] 2021-03-25 08:23
actually it was both...

So even simply:
```python
class MyModelManager(models.Manager['MyModel']):

    def create(self, *args, **kwargs) -> MyModel:
          return super().create(*args, **kwargs)


class MyModel(models.Model):

   objects = MyModelManager()
```

still raises `Signature of "create" incompatible with supertype "_BaseQuerySet"`.

**Comment by syastrov** [comment] 2021-06-27 21:19
I can't reproduce this. Both examples pass for me locally.
CI will probably agree:
https://github.com/typeddjango/django-stubs/pull/653

**Comment by sobolevn** [comment] 2021-06-28 00:19
I will close this, because #653 does not reproduce this issue.

Feel free to reopen / submit a reproducable example, so we can fix it!

**Closed as completed by sobolevn** 2021-06-28 00:19 UTC
Labels: bug
