### ISSUE TITLE
Typing for get_user_model()

### ISSUE THREAD

**Issue by markedwards** [typeddjango/django-stubs#599] opened 2021-04-21 11:25 UTC
# Bug report

Right now, typing for `get_user_model()` is implemented like:
```
def get_user_model() -> Type[Model]: ...
```

This is pretty useless for many cases, and inevitably results in a `cast` or a `# type: ignore`.

## How is that should be

This would be an improvement:
```
def get_user_model() -> Type[AbstractUser]: ...
```

Better yet, could django-stubs introspect settings and determine the real type that is returned?

## System information

- OS:
- `python` version: 3.9
- `django` version: 3.2
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0

**Comment by sobolevn** [comment] 2021-04-21 12:00
> Better yet, could django-stubs introspect settings and determine the real type that is returned?

We have some support of this function: https://github.com/typeddjango/django-stubs/blob/8f97bf880d3022772581ea4cf8b5bf5297a27bad/mypy_django_plugin/main.py#L201

Implementation: https://github.com/typeddjango/django-stubs/blob/8f97bf880d3022772581ea4cf8b5bf5297a27bad/mypy_django_plugin/transformers/settings.py#L11

We even have a test for it: https://github.com/typeddjango/django-stubs/blob/8f97bf880d3022772581ea4cf8b5bf5297a27bad/tests/typecheck/test_shortcuts.yml#L23

Do you have any problems with it? If so, please, provide a reproduction.

**Comment by markedwards** [comment] 2021-04-21 12:31
Ah I see, I jumped to an incorrect conclusion.  So the issue I have is actually that mypy ends up with a type alias which cannot be used for annotation:
```python
from django.contrib.auth import get_user_model

User = get_user_model()


def foo(pk: int) -> User:  # Variable "my.example.User" is not valid as a type
    return User.objects.get(pk)
```

**Comment by sobolevn** [comment] 2021-04-21 13:22
Yes, this is unrelated to `django-stubs` 😞 
This is how `mypy` works, it treats function calls as global variables, not type aliases.

You can use this:

```python
if TYPE_CHECKING:
    from your_app.models import User as UserType

User = get_user_model()
```

**Comment by sobolevn** [comment] 2021-04-21 13:22
I am going to close this, because there's nothing we can do!

**Closed as completed by sobolevn** 2021-04-21 13:22 UTC
Labels: bug

**Comment by markedwards** [comment] 2021-04-21 15:14
Thanks, sorry for the noise.  Sad that there's no better solution to this.

**Comment by robbrit** [comment] 2021-09-28 17:20
Was there any workaround discovered for this? I'm running into this problem now after moving to the latest version of django-stubs.

**Comment by theoden-dd** [comment] 2022-04-12 07:35
Just a note for successors. Fixing this [conditionally](https://github.com/typeddjango/django-stubs/issues/599#issuecomment-824056866) results in pytest collecting errors like below:
```
_______________ ERROR collecting server/drf.py _______________
server/drf.py:15: in <module>
    class PlatformJwtAuthentication(authentication.BaseAuthentication):
server/drf.py:22: in PlatformJwtAuthentication
    def authenticate(self, request) -> Union[None, Tuple[UserType, str]]:
E   NameError: name 'UserType' is not defined
```

For me it better worked unconditionally, just:
```
from your_app.models import User as UserType
```
