### ISSUE TITLE
Overriding AppConfig.default_auto_field incorrectly raises type error

### ISSUE THREAD

**Issue by markedwards** [typeddjango/django-stubs#1597] opened 2023-06-28 13:17 UTC
# Bug report

## What's wrong

This:
```python
class MyAppConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'  # raises type error -- Incompatible types in assignment (expression has type "str", base class "AppConfig" defined the type as "Callable[[AppConfig], str]")
```

## How is that should be

Overriding this with a string is the normal expected usage, so it should not raise any type error.

## System information

- OS:
- `python` version: 3.10.11
- `django` version: 4.2.1
- `mypy` version: 1.3.0
- `django-stubs` version: 4.2.2
- `django-stubs-ext` version: 4.2.2

**Comment by intgr** [comment] 2023-06-28 13:52
Duplicate of #1593

**Closed as completed** 2023-06-28 13:52 UTC
Labels: bug

**Comment by markedwards** [comment] 2023-06-28 16:04
Sorry, I did search for `default_auto_field` and didn’t get a result :-/
