### ISSUE TITLE
Incompatibility with mypy 0.78x

### ISSUE THREAD

**Issue by cihati** [typeddjango/django-stubs#435] opened 2020-07-30 09:59 UTC
# Bug report

## What's wrong
I recently upgrade to mypy 0.782 and I started seeing the following:

```
	 ERROR: django-stubs 1.5.0 has requirement mypy<0.780,>=0.770, but you'll have mypy 0.782 which is incompatible.
```

## System information

- OS:
- `python` version: 3.7.7
- `django` version: 2.2.13
- `mypy` version: 0.782
- `django-stubs` version: 1.5.0

**Comment by sobolevn** [comment] 2020-07-30 10:00
Duplicate of #388

**Closed as completed by sobolevn** 2020-07-30 10:00 UTC
Labels: bug
